### ISSUE TITLE
What is a GNU License?

### ISSUE THREAD

**Issue by pavanmahesh107** [BedBug2479/test-for-pr#1]
The GNU General Public License (GPL) is a widely used free software license, originally written by Richard Stallman for the GNU Project. It guarantees end users the freedom to run, study, share, and modify the software. The GPL is a copyleft license, meaning that derivative work can only be distributed under the same license terms. Here are key aspects of the GNU GPL.

**Comment by BedBug2479** [comment]
resolved #1
